### ISSUE TITLE
Update submodules

### ISSUE THREAD

**Issue by iboB** [alpaca-core/ilib-llama.cpp#1]
It's time to update our forks and submodules. Check for upstream updates and merge them if necessary.

Don't forget to use [the guide](https://github.com/alpaca-core/alpaca-core/blob/master/doc/dev/updating-submodules.md).

Subbmodules to update:

- [ ] llama.cpp

**Comment by pminev** [comment]
Added new chat template for granite in [this commit](https://github.com/ggerganov/llama.cpp/commit/61715d5cc83a28181df6a641846e4f6a740f3c74#diff-b87e1c2fc779778832f03ef373963fcc40603a0500fc13cdc4cc570ee0189e8fR67). Maybe we should add it to the tests?

**Comment by pminev** [comment]
Enabled KV cache defrag by default. [Commit](https://github.com/ggerganov/llama.cpp/commit/b141e5f6efbab3a00633df88c4f9425bfe8b78ab)

**Comment by pminev** [comment]
KV cache state is reverted in case of failed compute 

[commit](https://github.com/ggerganov/llama.cpp/commit/fb4a0ec0833c71cff5a1a367ba375447ce6106eb#diff-dd7c3bc82b7d2728f1fe661e7820aebbfd53f558a5fdd85bbd6dd618213a118dR800)

**Comment by pminev** [comment]
OLMo November 2024 support - [commit](https://github.com/ggerganov/llama.cpp/commit/a88ad007de3eb5d92cb538fd269ff94c4bf0c8d2)

**Comment by pminev** [comment]
new api `llama_kv_cache_can_shift` in [this commit](https://github.com/ggerganov/llama.cpp/commit/8e752a777b272606f22cb741b03e062de4ddb8fe)

**Comment by pminev** [comment]
Enabled cache prompt by default - [commit](https://github.com/ggerganov/llama.cpp/commit/47f931c8f9a26c072d71224bc8013cc66ea9e445)

**Comment by pminev** [comment]
Exposed [new API](https://github.com/ggerganov/llama.cpp/commit/642330ac7cea11dc1f9d3df2b8f3dbd10b5e3f3e#diff-dd7c3bc82b7d2728f1fe661e7820aebbfd53f558a5fdd85bbd6dd618213a118dR994) `llama_chat_builtin_templates ` for suppoted chat templates
