### ISSUE TITLE
llama: add control vector

### ISSUE THREAD

**Issue by iboB** [alpaca-core/ilib-llama.cpp#12]
*Intentionally skipped while implementing alpaca-core/ac-local#3*

We should be able to apply control vectors via `llama_control_vector_apply` 

(in main demo this is done by reading files in `llama_control_vector_load` from common lib)

**Comment by pminev** [comment]
To generate control vector follow: https://github.com/ggerganov/llama.cpp/tree/master/examples/cvector-generator
